name: Bug bounty
description: Report a bug
title: "[Bug Bounty]: "
labels: ["bug-bounty"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill outthe bug bounty submission
  - type: dropdown
    id: bug-type
    attributes:
      label: bug type
      multiple: false
      options:
        - proposal for a "private" like
        - double-like
        - withdraw someone else like
        - withdraw your like
    validations:
      required: true
  - type: textarea
    id: Steps-to-Reproduce
    attributes:
      label: Steps to Reproduce
      description: Describe step to reproduce the bug
    validations:
      required: true
  - type: checkboxes
    id: confidential
    attributes:
      label: Confidential issue
      options:
        - label: "in fact, it won't change anything. it's a little troll because github does not allow confidential issues (and certainly will not allow it)"
          required: false
