name: Bug bounty
description: Report a bug
title: "[Bug Bounty]: "
labels: ["bug-bounty"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill outthe bug bounty submission
  - type: input
    id: name
    attributes:
      label: template name
      description: The name of you template. It will be prefixed by your github username
      placeholder: ex. awesome-web-bug-bounty-report
    validations:
      required: true
  - type: dropdown
    id: bug-type
    attributes:
      label: bug type
      multiple: false
      options:
        - proposal for a "private" like
        - double-like
        - withdraw someone else like
        - withdraw your like
    validations:
      required: true
