name: Like
description: Add a like
title: "Add new like!"
labels: ["like"]
body:
  - type: markdown
    attributes:
      value: |
        Click on `Submit new issue` to validate your like
  - type: textarea
    id: useless
    attributes:
      label: useless
      description: Add something useless if you want, you are free
      placeholder: 🐛
    validations:
      required: false
