name: Add Like
on:
  issues:
    types:
      - labeled
jobs:
  add-like:
    env:
      author: ${{github.event.issue.user.login}}
    if: github.event.label.name == 'like'
    runs-on: ubuntu-latest
    name: commit and push like
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Create local changes
      run: |
        if grep -Fxq "$author" likers.txt
        then
        echo "Try again!"
        else
        echo "$author" >> likers.txt
        #and update counter
        LIKES=$(wc -l < likers.txt);REPLACE=$(echo "<b><i>Like counter: ${LIKES}</i><b>");(head -5 README.md; echo "$REPLACE"; tail -n +7 README.md) > foobar && mv foobar README.md
        fi
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
